spring.application.name=spring-email

# jackson
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true


# mongodb
spring.mongodb.authentication-database=admin
spring.data.mongodb.auto-index-creation=true
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=springemail
spring.mongodb.username=admin
spring.mongodb.password=admin

# email
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# security
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration=86400000

# ratelimiter
api.ratelimiter.email.limit-for-period=2
api.ratelimiter.email.limit-refresh-period=30s
api.ratelimiter.email.timeout-duration=0





