# mongodb
spring.mongodb.uri=mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOSTNAME}/${MONGO_DATABASE}?appName=${MONGO_CLUSTER}&retryWrites=true&w=majority

# email
spring.mail.host=${SMTP_HOSTNAME}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
